---

- name: Get service information
  ansible.builtin.service_facts:
  register: service_facts
  tags:
    - satellite-install
    - satellite-install-firewall

- name: Add RH-Satellite-6 service to firewalld
  when: service_facts.ansible_facts.services['firewalld.service'] is defined and service_facts.ansible_facts.services['firewalld.service']['state'] == 'running'
  ansible.posix.firewalld:
    service: RH-Satellite-6
    permanent: true
    state: enabled
  tags:
    - satellite-install
    - satellite-install-firewall

- name: Add RH-Satellite-6 service to running firewalld
  when: service_facts.ansible_facts.services['firewalld.service'] is defined and service_facts.ansible_facts.services['firewalld.service']['state'] == 'running'
  ansible.posix.firewalld:
    service: RH-Satellite-6
    permanent: false
    state: enabled
  tags:
    - satellite-install
    - satellite-install-firewall

- name: Add dhcp to firewalld
  when: service_facts.ansible_facts.services['dhcpd.service'] is defined and service_facts.ansible_facts.services['dhcpd.service']['state'] == 'running'
  ansible.posix.firewalld:
    service: dhcp
    permanent: true
    state: enabled
  tags:
    - satellite-install
    - satellite-install-firewall

- name: Add dhcp to running firewalld
  when: service_facts.ansible_facts.services['dhcpd.service'] is defined and service_facts.ansible_facts.services['dhcpd.service']['state'] == 'running'
  ansible.posix.firewalld:
    service: dhcp
    permanent: false
    state: enabled
  tags:
    - satellite-install
    - satellite-install-firewall
