---

- name: Enable Red Hat Satellite subscription # noqa: args[module]
  when: activation['activation_key'] is defined or activation['username'] is defined
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ activation.activation_key | default(omit) }}"
    org_id: "{{ activation.org_id | default(omit) }}"
    username: "{{ activation.username | default(omit) }}"
    password: "{{ activation.password | default(omit) }}"
    pool: '^Red Hat Satellite.*$'
  tags:
    - satellite-install
    - satellite-install-repos

- name: Enable Repos for RHEL 8
  become: true
  when: ansible_distribution_major_version == "8"
  community.general.rhsm_repository:
    purge: true
    name: "{{ repos8 }}"
  tags:
    - satellite-install
    - satellite-install-repos

- name: Enable RHEL 8 modules
  become: true
  when: ansible_distribution_major_version == "8"
  ansible.builtin.command: # noqa: no-changed-when
    cmd: "dnf module enable -y {{ modules8 | join(' ') }}"
  tags:
    - satellite-install
    - satellite-install-repos
